# Generated by tools/build_pickup_sprites.py. Do not hand-edit.
extends RefCounted

const ART = {
    "source": "Freedoom v0.13.0",
    "pickups": {
        "medkit": {
            "size": [
                29,
                20
            ],
            "frames": [
                "media0"
            ],
            "source_bounds": [
                [
                    0,
                    0,
                    29,
                    20
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ]
            ],
            "source_dir": "freedoom",
            "width": 0.85,
            "fps": 0.0,
            "lift": 0.0,
            "bob": 0.0
        },
        "stim": {
            "size": [
                19,
                10
            ],
            "frames": [
                "stima0"
            ],
            "source_bounds": [
                [
                    0,
                    0,
                    19,
                    10
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ]
            ],
            "source_dir": "freedoom",
            "width": 0.38,
            "fps": 0.0,
            "lift": 0.0,
            "bob": 0.0
        },
        "armor": {
            "size": [
                37,
                28
            ],
            "frames": [
                "arm1a0",
                "arm1b0"
            ],
            "source_bounds": [
                [
                    0,
                    0,
                    37,
                    28
                ],
                [
                    0,
                    0,
                    37,
                    28
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ],
                [
                    0,
                    0
                ]
            ],
            "source_dir": "freedoom",
            "width": 0.85,
            "fps": 3.0,
            "lift": 0.0,
            "bob": 0.0
        },
        "bullets": {
            "size": [
                17,
                16
            ],
            "frames": [
                "ammoa0"
            ],
            "source_bounds": [
                [
                    0,
                    0,
                    17,
                    16
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ]
            ],
            "source_dir": "freedoom",
            "width": 0.62,
            "fps": 0.0,
            "lift": 0.0,
            "bob": 0.0
        },
        "shells": {
            "size": [
                34,
                13
            ],
            "frames": [
                "sboxa0"
            ],
            "source_bounds": [
                [
                    0,
                    0,
                    34,
                    13
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ]
            ],
            "source_dir": "freedoom",
            "width": 0.8,
            "fps": 0.0,
            "lift": 0.0,
            "bob": 0.0
        },
        "rockets": {
            "size": [
                52,
                20
            ],
            "frames": [
                "broka0"
            ],
            "source_bounds": [
                [
                    0,
                    0,
                    52,
                    20
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ]
            ],
            "source_dir": "freedoom",
            "width": 1.0,
            "fps": 0.0,
            "lift": 0.0,
            "bob": 0.0
        },
        "cells": {
            "size": [
                32,
                20
            ],
            "frames": [
                "celpa0"
            ],
            "source_bounds": [
                [
                    0,
                    0,
                    32,
                    20
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ]
            ],
            "source_dir": "freedoom",
            "width": 0.72,
            "fps": 0.0,
            "lift": 0.0,
            "bob": 0.0
        },
        "bluekey": {
            "size": [
                56,
                35
            ],
            "frames": [
                "bluecard0",
                "bluecard1"
            ],
            "source_bounds": [
                [
                    4,
                    3,
                    56,
                    35
                ],
                [
                    4,
                    3,
                    56,
                    35
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ],
                [
                    0,
                    0
                ]
            ],
            "source_dir": "keycards",
            "width": 0.72,
            "fps": 4.0,
            "lift": 0.1,
            "bob": 0.025
        },
        "redkey": {
            "size": [
                56,
                35
            ],
            "frames": [
                "redcard0",
                "redcard1"
            ],
            "source_bounds": [
                [
                    4,
                    3,
                    56,
                    35
                ],
                [
                    4,
                    3,
                    56,
                    35
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ],
                [
                    0,
                    0
                ]
            ],
            "source_dir": "keycards",
            "width": 0.72,
            "fps": 4.0,
            "lift": 0.1,
            "bob": 0.025
        },
        "mega": {
            "size": [
                25,
                25
            ],
            "frames": [
                "soula0",
                "soulb0",
                "soulc0",
                "sould0"
            ],
            "source_bounds": [
                [
                    0,
                    0,
                    25,
                    25
                ],
                [
                    0,
                    0,
                    25,
                    25
                ],
                [
                    0,
                    0,
                    25,
                    25
                ],
                [
                    0,
                    0,
                    25,
                    25
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ],
                [
                    0,
                    0
                ],
                [
                    0,
                    0
                ],
                [
                    0,
                    0
                ]
            ],
            "source_dir": "freedoom",
            "width": 0.78,
            "fps": 6.0,
            "lift": 0.24,
            "bob": 0.05
        },
        "suit": {
            "size": [
                23,
                52
            ],
            "frames": [
                "suita0"
            ],
            "source_bounds": [
                [
                    0,
                    0,
                    23,
                    52
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ]
            ],
            "source_dir": "freedoom",
            "width": 0.62,
            "fps": 0.0,
            "lift": 0.0,
            "bob": 0.0
        },
        "shotgun": {
            "size": [
                38,
                13
            ],
            "frames": [
                "shota0"
            ],
            "source_bounds": [
                [
                    0,
                    0,
                    38,
                    13
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ]
            ],
            "source_dir": "freedoom",
            "width": 1.35,
            "fps": 0.0,
            "lift": 0.0,
            "bob": 0.0
        },
        "chaingun": {
            "size": [
                50,
                25
            ],
            "frames": [
                "mguna0"
            ],
            "source_bounds": [
                [
                    0,
                    0,
                    50,
                    25
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ]
            ],
            "source_dir": "freedoom",
            "width": 1.35,
            "fps": 0.0,
            "lift": 0.0,
            "bob": 0.0
        },
        "launcher": {
            "size": [
                59,
                20
            ],
            "frames": [
                "launa0"
            ],
            "source_bounds": [
                [
                    0,
                    0,
                    59,
                    20
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ]
            ],
            "source_dir": "freedoom",
            "width": 1.45,
            "fps": 0.0,
            "lift": 0.0,
            "bob": 0.0
        },
        "plasma": {
            "size": [
                51,
                16
            ],
            "frames": [
                "plasa0"
            ],
            "source_bounds": [
                [
                    0,
                    0,
                    51,
                    16
                ]
            ],
            "origins": [
                [
                    0,
                    0
                ]
            ],
            "source_dir": "freedoom",
            "width": 1.35,
            "fps": 0.0,
            "lift": 0.0,
            "bob": 0.0
        }
    }
}
