# Generated by tools/build_redot_chan.py.
extends RefCounted

const ART = {
  "size": [
    42,
    44
  ],
  "columns": 8,
  "rows": 1,
  "expressions": {
    "calm": 0,
    "happy": 1,
    "hurt": 2,
    "tired": 3,
    "panic": 4,
    "confident": 5,
    "defeated": 6,
    "focused": 7
  },
  "source_crops": {
    "calm": [
      77,
      58,
      190,
      208
    ],
    "happy": [
      324,
      39,
      192,
      218
    ],
    "hurt": [
      583,
      35,
      186,
      228
    ],
    "tired": [
      77,
      306,
      190,
      231
    ],
    "panic": [
      305,
      286,
      198,
      251
    ],
    "confident": [
      563,
      300,
      191,
      238
    ]
  },
  "eye_anchor": [
    21,
    25
  ],
  "source_eyes": {
    "calm": [
      155,
      169
    ],
    "happy": [
      423,
      173
    ],
    "hurt": [
      704,
      159
    ],
    "tired": [
      151,
      423
    ],
    "panic": [
      406,
      408
    ],
    "confident": [
      698,
      434
    ]
  },
  "credit": "User-supplied Redot-chan concept 2.0 / DLC 2 sheet, signed Rune"
}
