# Generated by tools/build_weapon_sprites.py. Do not hand-edit.
extends RefCounted

const ART = {
    "source": "Freedoom v0.13.0",
    "canvas": [
        320,
        200
    ],
    "hand_style": "Redot-chan / warm porcelain skin, slender wrists, black sleeves, red cuffs",
    "hand_palettes": {
        "skin": [
            "382b37",
            "84545d",
            "ae7277",
            "cf9290",
            "eeb0a4",
            "f7cab5",
            "ffdeca",
            "ffeddb"
        ],
        "sleeve": [
            "10111a",
            "191821",
            "24212c",
            "312b38",
            "403644"
        ],
        "cuff": [
            "5a242b",
            "9e3436",
            "d95049",
            "f47b66"
        ]
    },
    "weapons": {
        "fist": {
            "body_bounds": [
                [
                    100,
                    131,
                    89,
                    43
                ],
                [
                    64,
                    150,
                    252,
                    26
                ],
                [
                    196,
                    111,
                    105,
                    69
                ],
                [
                    146,
                    88,
                    174,
                    88
                ]
            ],
            "flash_bounds": [],
            "body_origins": [
                [
                    96,
                    128
                ],
                [
                    64,
                    144
                ],
                [
                    192,
                    108
                ],
                [
                    144,
                    84
                ]
            ],
            "flash_origins": [],
            "hand_layer": "redot_hands/fist",
            "hand_mask": "redot_hands/fist_mask",
            "body_frames": [
                "punga0",
                "pungb0",
                "pungc0",
                "pungd0"
            ],
            "flash_frames": []
        },
        "pistol": {
            "body_bounds": [
                [
                    134,
                    97,
                    64,
                    92
                ],
                [
                    134,
                    82,
                    64,
                    96
                ],
                [
                    133,
                    87,
                    66,
                    100
                ],
                [
                    134,
                    76,
                    66,
                    106
                ],
                [
                    133,
                    68,
                    67,
                    120
                ]
            ],
            "flash_bounds": [
                [
                    144,
                    69,
                    32,
                    30
                ]
            ],
            "body_origins": [
                [
                    125,
                    97
                ],
                [
                    125,
                    82
                ],
                [
                    124,
                    87
                ],
                [
                    125,
                    76
                ],
                [
                    123,
                    68
                ]
            ],
            "flash_origins": [
                [
                    144,
                    69
                ]
            ],
            "hand_layer": "redot_hands/pistol",
            "hand_mask": "redot_hands/pistol_mask",
            "body_frames": [
                "pisga0",
                "pisgb0",
                "pisgc0",
                "pisgd0",
                "pisge0"
            ],
            "flash_frames": [
                "pisfa0"
            ]
        },
        "shotgun": {
            "body_bounds": [
                [
                    123,
                    107,
                    66,
                    62
                ],
                [
                    78,
                    40,
                    88,
                    128
                ],
                [
                    60,
                    25,
                    92,
                    143
                ],
                [
                    44,
                    39,
                    104,
                    129
                ]
            ],
            "flash_bounds": [
                [
                    142,
                    98,
                    36,
                    47
                ],
                [
                    131,
                    90,
                    58,
                    55
                ]
            ],
            "body_origins": [
                [
                    122,
                    107
                ],
                [
                    78,
                    40
                ],
                [
                    60,
                    25
                ],
                [
                    44,
                    39
                ]
            ],
            "flash_origins": [
                [
                    142,
                    98
                ],
                [
                    131,
                    90
                ]
            ],
            "hand_layer": "redot_hands/shotgun",
            "hand_mask": "redot_hands/shotgun_mask",
            "body_frames": [
                "shtga0",
                "shtgb0",
                "shtgc0",
                "shtgd0"
            ],
            "flash_frames": [
                "shtfa0",
                "shtfb0"
            ]
        },
        "chaingun": {
            "body_bounds": [
                [
                    107,
                    117,
                    106,
                    51
                ],
                [
                    107,
                    121,
                    106,
                    47
                ]
            ],
            "flash_bounds": [
                [
                    126,
                    98,
                    68,
                    37
                ],
                [
                    128,
                    111,
                    64,
                    23
                ]
            ],
            "body_origins": [
                [
                    107,
                    117
                ],
                [
                    107,
                    121
                ]
            ],
            "flash_origins": [
                [
                    126,
                    98
                ],
                [
                    128,
                    111
                ]
            ],
            "hand_layer": "",
            "hand_mask": "",
            "body_frames": [
                "chgga0",
                "chggb0"
            ],
            "flash_frames": [
                "chgfa0",
                "chgfb0"
            ]
        },
        "launcher": {
            "body_bounds": [
                [
                    111,
                    104,
                    99,
                    64
                ],
                [
                    107,
                    106,
                    106,
                    62
                ]
            ],
            "flash_bounds": [
                [
                    110,
                    99,
                    100,
                    63
                ],
                [
                    110,
                    94,
                    100,
                    68
                ],
                [
                    111,
                    96,
                    98,
                    64
                ],
                [
                    115,
                    91,
                    90,
                    63
                ]
            ],
            "body_origins": [
                [
                    111,
                    104
                ],
                [
                    107,
                    106
                ]
            ],
            "flash_origins": [
                [
                    110,
                    99
                ],
                [
                    110,
                    94
                ],
                [
                    111,
                    96
                ],
                [
                    115,
                    91
                ]
            ],
            "hand_layer": "",
            "hand_mask": "",
            "body_frames": [
                "misga0",
                "misgb0"
            ],
            "flash_frames": [
                "misfa0",
                "misfb0",
                "misfc0",
                "misfd0"
            ]
        },
        "plasma": {
            "body_bounds": [
                [
                    115,
                    104,
                    126,
                    76
                ],
                [
                    50,
                    100,
                    126,
                    68
                ]
            ],
            "flash_bounds": [
                [
                    115,
                    86,
                    126,
                    90
                ],
                [
                    115,
                    85,
                    126,
                    91
                ]
            ],
            "body_origins": [
                [
                    115,
                    104
                ],
                [
                    50,
                    100
                ]
            ],
            "flash_origins": [
                [
                    115,
                    86
                ],
                [
                    115,
                    85
                ]
            ],
            "hand_layer": "",
            "hand_mask": "",
            "body_frames": [
                "plsga0",
                "plsgb0"
            ],
            "flash_frames": [
                "plsfa0",
                "plsfb0"
            ]
        }
    }
}
